server:
  port: 8081

spring:
  jpa:
    # Driver Class = org.h2.Driver
    # JDBC URL = jdbc:h2:mem:testdb
    database-platform: H2
    show-sql: TRUE
    hibernate:
      ddl-auto: 'create-drop'
  security:
    user:
      name: auth
      password: test

spring.h2.console:
  enabled: true
  path: /h2-console