server:
  port: 8081

spring:
  jpa:
    # Driver Class = org.h2.Driver
    # JDBC URL = jdbc:h2:mem:testdb
    database-platform: H2
    show-sql: TRUE
    hibernate:
      ddl-auto: 'create-drop'

spring.h2.console:
  enabled: true
  path: /h2-console

security:
  oauth2:
    resource:
      # Authorization Server에서 Token정보를 받아옴
      token-info-uri: http://localhost:8082/oauth/check_token